import React, { useEffect } from 'react'
import Head from 'next/head'
import Gallery from '../components/Gallery'
import { useRouter } from "next/router";
import useStateContext from '../context/ContextProvider';

const Favorites = () => {
    const { user } = useStateContext();
    
    const router = useRouter();

    useEffect(() => {
        if (!user) {
            router.push("/");
        }
    }, [user, router])
    return (
        <div className='lg:pt-[130px] pt-[85px] px-[10px]' >
            <Head>
                <title>MIB4u | Favorites</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>
            <h1 className='text-[28px] md:text-[36px] font-bold text-center text-zinc-200 mb-[50px] md:mb-[80px]' >Favorites</h1>
            <Gallery findFavorite={true} />
        </div>
    )
}

export default Favorites