import { useEffect } from 'react';
import Head from 'next/head'
import IconButton from '@mui/material/IconButton';
import Categories from '../components/Categories'
import Gallery from '../components/Gallery'
import useStateContext from '../context/ContextProvider';
import { getCookie } from "cookies-next";
import jwt from "jsonwebtoken";




const Home = ({ googleUser }) => {
  const { work, limitIncrement, setUser } = useStateContext();
  useEffect(() => {
    if (googleUser) {
      setUser(googleUser);
    }
  }, [googleUser, setUser])
  return (
    <div className='lg:pt-[130px] pt-[85px] px-[10px]' >
      <Head>
        <title>MIB4u | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Categories />

      <Gallery findAll={true} />

      {work &&
        work.count > work.Work.length &&
        <div className='w-full flex justify-center' >
          <IconButton onClick={limitIncrement} className='text-[16px]' >
            <p className={`px-[60px] text-[16px] py-[6px] outline-none rounded-md text-gray-200 my-1 border border-transparent  font-semibold transition-all bg-emerald-500 hover:opacity-80 duration-300`}>Load more</p>
          </IconButton>
        </div>
      }
    </div>
  )
}

export async function getServerSideProps({ req, res }) {
  const token = getCookie("token", { req, res });
  if (token) {
    const verified = jwt.verify(token, process.env.JWT_KEY)
    return { props: { googleUser: verified } }
  } else {
    return { props: { googleUser: "" } }
  }

}
export default Home;
