import React, { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import ManageAccountsIcon from '@mui/icons-material/ManageAccounts';
import CollectionsIcon from '@mui/icons-material/Collections';
import PagesIcon from '@mui/icons-material/Pages';
import Head from 'next/head'
import useStateContext from '../context/ContextProvider';
import AddWork from '../components/settings/AddWork';
import EditUser from '../components/settings/EditUser';
import EditWork from '../components/settings/EditWork';
import { Tooltip } from '@mui/material';
import { useRouter } from "next/router";




const MyAccount = () => {
    const { submitEditUserForm, submitWorkForm, user, openModal, toUpdateWork, findOneWork, updateWork } = useStateContext();
    const router = useRouter();

    useEffect(()=>{
        if(!user){
            router.push("/");
        }
    },[router, user])

    // switch button to toggle between "Edit account" and "Adcd webd work"
    const [switchState, setSwitchState] = useState("edit");
    const switchHandler = (target) => {
        setSwitchState(target)
    }
    return (
        <div className={`w-screen h-fit lg:min-h-screen lg:pt-[130px] pt-[85px] text-gray-300 ${styles.fadeinAnime}`} >
            <Head>
                <title>MIB4u | My Account</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>
            <h1
                className={`text-[28px] md:text-[36px] font-bold text-center text-zinc-200 mb-[50px] md:mb-[80px] ${switchState === "edit" ? styles.modalOpen : styles.modalOff}`}
            >
                Edit account
            </h1>
            <h1
                className={`text-[28px] md:text-[36px] font-bold text-center text-zinc-200 mb-[50px] md:mb-[80px] ${switchState === "addWork" ? styles.modalOpen : styles.modalOff}`}
            >
                Add work
            </h1>
            <h1
                className={`text-[28px] md:text-[36px] font-bold text-center text-zinc-200 mb-[50px] md:mb-[80px] ${switchState === "editWork" ? styles.modalOpen : styles.modalOff}`}
            >
                Edit work
            </h1>


            <div className='w-full h-full flex flex-col lg:flex-row items-center lg:items-start justify-center gap-6 px-[20px]' >

                <div style={{ boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px" }} className='bg-zinc-800 w-full lg:w-[280px] flex lg:flex-col rounded-md h-fit overflow-hidden' >
                    <Tooltip title={"You can update your work"} placement="left" arrow >
                        <div onClick={() => switchHandler("edit")} className={`flex flex-1 justify-center lg:justify-start items-center gap-2 text-gray-300 text-[12px] md:text-[14px] font-bold md:px-4 py-3 hover:bg-zinc-600 transition-all cursor-pointer ${switchState === "edit" ? "bg-zinc-700" : "bg-zinc-800"}`} >
                            <ManageAccountsIcon />
                            <p>Edit account</p>
                        </div>
                    </Tooltip>

                    <Tooltip title={user.isAdmin ? "You can add your work" : "Only admin is allowed!"} placement="left" arrow >
                        <div onClick={() => user.isAdmin && switchHandler("addWork")} className={`flex justify-center lg:justify-start flex-1 items-center border-x lg:border-x-0 gap-2 text-gray-300 text-[12px] md:text-[14px] font-bold lg:border-t border-zinc-700 md:px-4 py-3 hover:bg-zinc-600 transition-all ${user.isAdmin ? "cursor-pointer" : "cursor-[not-allowed]"} ${switchState === "addWork" ? "bg-zinc-700" : "bg-zinc-800"}`} >
                            <CollectionsIcon />
                            <p>Add work</p>
                        </div>
                    </Tooltip>
                    <Tooltip title={user.isAdmin ? "You can edit your work" : "Only admin is allowed!"} placement="left" arrow >
                        <div onClick={() => user.isAdmin && switchHandler("editWork")} className={`flex flex-1 justify-center lg:justify-start items-center gap-2 text-gray-300 text-[12px] md:text-[14px] font-bold lg:border-t border-zinc-700 md:px-4 py-3 hover:bg-zinc-600 transition-all ${user.isAdmin ? "cursor-pointer" : "cursor-[not-allowed]"} ${switchState === "editWork" ? "bg-zinc-700" : "bg-zinc-800"}`} >
                            <PagesIcon />
                            <p>Edit work</p>
                        </div>
                    </Tooltip>
                </div>
                {/* Edit user form */}
                <EditUser
                    submitEditUserForm={submitEditUserForm}
                    switchState={switchState}
                    user={user}
                />
                {/* Add Work form */}
                <AddWork
                    submitWorkForm={submitWorkForm}
                    switchState={switchState}
                    user={user}
                />
                {/* Edit work form */}
                <EditWork
                    switchState={switchState}
                    user={user}
                    open={openModal}
                    toUpdateWork={toUpdateWork}
                    updateWork={updateWork}
                    findOneWork={findOneWork}

                />

            </div>
        </div>
    )
}

export default MyAccount