import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'



const privacy = () => {
    return (
        <div className={`w-screen min-h-screen lg:pt-[130px] pt-[85px] text-gray-300 flex justify-center px-[40px] ${styles.fadeinAnime}`} >
               <Head>
        <title>MIB4u | Privacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
            <div className='lg:w-[65vw] w-full' >
                <h1 className='text-[28px] md:text-[36px] font-bold text-center text-zinc-200 mb-[50px] md:mb-[80px]' >Privacy</h1>
                <h1 className='text-[20px] font-bold text-zinc-200 mb-4' >MIB4u</h1>
                <ol className='list-outside list-disc mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        Personal data is always specifically requested from you and is only recorded by MIB4u Gallery with your permission.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery does its best to correctly register the data you entered and, where possible, allows you to adjust your data.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The e-mail address entered by you is used by our &quot;forgot password service&quot;. This allows you to request your password if you have forgotten it. A short newsletter is also periodically sent to the participating artists, unsubscribing is possible via the unsubscribe link at the bottom of the newsletter.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery reserves the right to adjust this privacy statement. The most current version will be available on this page at any time.
                    </li>

                    <li className='text-[15px] text-zinc-500' >

                    </li>

                </ol>
                <h2 className='font-semibold text-zinc-400 mb-3' >Below you will find our complete Privacy Policy.</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    Privacy sensitive data or personal data is processed via MIB4u Gallery. MIB4u Gallery considers careful handling of personal data of great importance. Personal data is therefore carefully processed and secured by us.
                </p>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    In our processing we adhere to the requirements of the privacy legislation. That means among other things that:
                </p>
                <ol className='list-outside list-disc mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        We clearly state the purposes for which we process personal data. We do this through this privacy statement;
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        We limit our collection of personal data to only the personal data required for legitimate purposes;
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        We first ask you for explicit permission to process your personal data in cases where your permission is required;
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        We take appropriate security measures to protect your personal data and that also demands of parties that process personal data on our behalf;
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        We respect your right to offer, correct or delete your personal data on your request.
                    </li>
                </ol>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    MIB4u Gallery is responsible for data processing. In this privacy statement we explain which personal data we collect and use and for what purpose. We recommend that you read this carefully.
                </p>
                <h2 className='font-semibold text-zinc-400 mb-3' >Use of personal data</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    When using our web store we obtain certain information from you. That may be personal data. We only store and use the personal data that is provided directly by you, in the context of the service you have requested, or for which it is clear that it is provided to us for processing.
                </p>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We use the following data for the purposes stated in this privacy statement:
                </p>
                <ol className='list-outside list-disc mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        Name and address data
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Telephone number
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Billing address
                    </li>

                    <li className='text-[15px] text-zinc-500' >
                        E-mail address
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Payment details
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Your username
                    </li>
                </ol>
                <h2 className='font-semibold text-zinc-400 mb-3' >Register</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    With a purchase in our web store you have the choice to register. After registration, we store the personal details you provide via the user name you have chosen. We save this information so that you do not have to enter it every time and so that we can contact you in the context of the implementation of the agreement.
                </p>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We will not provide the data linked to your username to third parties, unless this is necessary in the context of the implementation of the agreement that you conclude with us or if this is required by law. In the event of a suspicion of fraud or misuse of our web store, we may hand over personal data to the competent authorities.
                </p>
                <h2 className='font-semibold text-zinc-400 mb-3' >Portal access</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    With our portal you can access a management environment where you can set, specify and change things yourself.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Process order</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    When you place an order with us, we use your personal data to process it. If necessary for proper handling, we can also provide your personal data to third parties. You can read more about this later in this privacy statement.
                </p>
                <h2 className='font-semibold text-zinc-400 mb-3' >Take out a subscription</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    As an artist you can take out a paid subscription via www.onlinegallery.art. For this purpose we ask you for the data required for payment. These are not used for other purposes.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Advertisement</h2>
                <ol className='list-outside list-disc mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        E-mail
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Social media
                    </li>
                </ol>

                <p className='text-[15px] text-zinc-500 mb-3' >
                    In addition to the information on our website, we can also inform you about our new products and services:
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Contact form and newsletter</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We offer the possibility to ask questions via an e-mail address through our web store. You choose yourself which data you provide. The data that you send to us will be kept for as long as the nature of the form or the content of your e-mail requires it to be fully answered and processed.
                </p>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We offer a newsletter with which we want to inform interested parties about our products and / or services. Every newsletter contains a link that you can use to unsubscribe. Your e-mail address is automatically added to the list of subscribers.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Publication</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We do not publish your customer data.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Distribution to third parties</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We can pass on your details to our partners. These partners are involved in the implementation of the agreement. These partners are (also) established outside the EU. Social media buttons may be included on the websites of the artists of MIB4u Gallery. With this, the administrators of these services collect your personal data. You will find a cookie report on the relevant websites.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Google Analytics</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We use Google Analytics to keep track of how visitors use our web store. We have entered into a data processing agreement with Google to make agreements about how to use our data. Furthermore, we have not allowed Google to use the obtained Analytics information for other Google services. Finally, we have the IP addresses anonymized.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Security</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We take security measures to limit abuse of and unauthorized access to personal data.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Retention periods</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    The personal details described above are kept for as long as necessary to process your orders, including warranty. We then save data for a maximum of one year for the statistical purposes described. The data is then deleted, unless there is a legal obligation that requires longer storage (such as the tax retention obligation of seven years for payment data).
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Third party websites</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    This privacy statement does not apply to third-party websites that are connected to our webshop through links. We cannot guarantee that these third parties will handle your personal data in a reliable or safe manner. We recommend that you read the privacy statement of these websites before using these websites.
                </p>

                <h2 className='font-semibold text-zinc-400 mb-3' >Changes to this privacy statement</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    We reserve the right to make changes to this privacy statement. It is recommended that you regularly consult this privacy statement so that you are aware of these changes.
                </p>
                <h2 className='font-semibold text-zinc-400 mb-3' >View and change your data</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    For questions about our privacy policy or questions regarding access and changes to (or deletion of) your personal data, you can contact us at any time via the details below.
                </p>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    You can also send us a request to view, change or delete this data. You can also submit a request to request a data export for data that we use with your permission, or state with reasons that you want us to limit the processing of personal data.
                </p>
                <p className='text-[15px] text-zinc-500 mb-3' >
                    To prevent abuse, we can ask you to identify yourself adequately. When it comes to access to personal data linked to a cookie, you must send a copy of the cookie in question. You can find this in the settings of your browser. If the data is incorrect, you can request us to change the data or have it deleted.
                </p>

            </div>
        </div>
    )
}

export default privacy