import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'



const TermsConditions = () => {
    return (
        <div className={`w-screen min-h-screen lg:pt-[130px] pt-[85px] text-gray-300 flex justify-center px-[40px] ${styles.fadeinAnime}`} >
            <div className='lg:w-[65vw] w-full' >
                <Head>
                    <title>MIB4u | Terms & Conditions</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/images/favicon.png" />
                </Head>
                <h1 className='text-[28px] md:text-[36px] font-bold text-center text-zinc-200 mb-[50px] md:mb-[80px]' >Terms and Conditions</h1>
                <h1 className='text-[20px] font-bold text-zinc-200 mb-4' >MIB4u</h1>

                {/* Article 1 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 1. | DEFINITIONS</h2>
                <p className='text-[15px] text-zinc-500 mb-3' >In these general terms and conditions, the following terms, always indicated with a capital letter, are used in the following sense.</p>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery: Online Galerij B.V., the user of these general terms and conditions, established at Schoolstraat 1, 2271BZ in Voorburg, the Netherlands, registered in the Trade Register under Chamber of Commerce number 74764225.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Art Lover: any natural or legal person who makes use of the Platform as a (potential) buyer of one or more Products.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Consumer: an Art Lover, a natural person, not acting in the course of a profession or business.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Agreement: any agreement between the Art Lover and a Seller that is concluded directly through the Platform&apos;s ordering or auction system and which provides for the delivery by the Seller of one or more Products. &apos;Agreement&apos;, in the meaning of these general terms and conditions, does not mean an agreement between the Art Lover and the Seller which is not concluded by means of the Platform&apos;s ordering or auction system, but in the context of which the Art Lover has contacted the Seller directly, whether or not on the basis of the Seller&apos;s contact details stated in or with the Offer.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Platform: <a className='text-violet-500 underline' href='https://www.mib4u.com' >www.mib4u.com</a> .
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Offer: any offer by the Seller concerning Products directed to the Art Lover via the Platform.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Seller: any natural or legal person affiliated with MIB4u Gallery who offers and sells Products through the Platform.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Products: the items to be sold and delivered by the Seller to the Art Lover within the framework of a Purchase Agreement, which may include various art articles.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Service: the performance to which MIB4u Gallery undertakes towards the Art Lover and Sellers in the context of the exploitation of the Platform, which may include, but is not limited to, the publication of the Offer of Sellers, the facilitation of the conclusion of Agreements, the forwarding of orders to Sellers and the settlement of relevant payments.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        In writing: communication in writing, communication by e-mail or any other means of communication that can be equated with this in view of the state of the art and the prevailing views in society.
                    </li>

                </ol>

                {/* Article 2 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 2. | GENERAL PROVISIONS</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        These general terms and conditions apply to the use of the Platform by the Art Lover and the Service directed to the Art Lover.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery is only involved as an intermediary in the Offer and in the Agreements. The relevant Seller is responsible and liable for the Offer, the quality of the Products (promised to the Art Lover) and their delivery to the relevant Art Lover.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Annulment or nullity of one or more of the provisions of these general terms and conditions shall not affect the validity of the remaining provisions. In such a case, the Art Lover and MIB4u Gallery are obliged to consult with each other in order to make a replacement arrangement with regard to the affected clause. As far as possible, the aim and scope of the original provision shall be taken into account.
                    </li>

                </ol>

                {/* Article 3 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 3. | ABOUT ONLINE GALLERY, REGISTRATION, OFFER & CREATION OF AGREEMENTS</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        The Platform offers the Art Lover the possibility to buy Products from Sellers. Sellers may use the order or auction system on the Platform or choose to include their contact details in or with the Offer so that the Art Lover can contact the Seller directly to enter into a purchase agreement. In the latter case MIB4u Gallery is in no way involved in the conclusion and settlement of the aforementioned purchase agreements and accepts no liability whatsoever in this respect. In the case of an Agreement (thus as referred to in article 1.4 and which is concluded directly through the order or auction system on the Platform), MIB4u Gallery enters into the Agreement with the relevant Seller on behalf of the Art Lover. The Seller shall at all times independently take care of the delivery of the Products to the Art Lover. Within the framework of an Agreement, the Art Lover will fulfil its payment obligations under the Agreement to MIB4u Gallery.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        To be able to enter into agreements, the Art Lover, after he has registered on the Platform and after this registration has been approved by MIB4u Gallery, will receive login details to access his account on the Platform. When registering, the Art Lover must provide all the required mandatory information completely and truthfully.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The Art Lover is not allowed to have more than one account on the Platform at the same time.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The Art Lover must keep his login details strictly confidential in order to access his account. He may not make his account available to third parties. All actions carried out under the Art Lover&apos;s account shall be attributed to the registered Art Lover.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The information contained in the Offer is determined by the respective Seller, for whose content MIB4u Gallery is not responsible. MIB4u Gallery is therefore not liable because the Service is based on incorrect or incomplete information provided by the Seller.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The Sellers are responsible and liable for correct and complete information about the Products they offer. The Offer will be displayed on the Platform in accordance with the data uploaded by the relevant Seller, including any images. However, product images shown in the Offer can only be regarded as indicative. The data mentioned in the Offer may differ slightly from what is actually supplied. Minor deviations are all deviations in characteristics of the Products that the Art Lover should reasonably tolerate. The presence of minor deviations does not provide the Art Lover with any grounds for complaints, for suspending its obligations under the Agreement, for dissolving the Agreement, or for claiming compensation in damages or any other compensation.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        An Agreement concerning a simple purchase will be concluded when the Art Lover has accepted the Seller&apos;s offer and the Art Lover has complied with all the conditions expressly attached to the acceptance of the Offer. MIB4u Gallery will then confirm the order by e-mail as soon as possible.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        If the Art Lover participates in an auction on the Platform, the Art Lover may, during the term of the auction, submit a bid that exceeds the minimum price indicated by the Seller. The duration of the auction shall be extended by a maximum of ten minutes, provided that at least two bids have been submitted, to enable the other bidder or bidders to exceed the highest bid so far. Other bidders will be notified of this by email. If the Art Lover has submitted the highest bid after the expiry of the final term of the auction, it shall claim delivery of the Product by the Seller and the Art Lover shall be obliged to purchase the Product from the Seller. MIB4u Gallery will send a confirmation and payment link to the Art Lover concerned in order to make the agreed payment.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The Art Lover must provide all compulsory (name and address) information requested for the purpose of entering into the Agreement correctly and completely. The Agreement can only be implemented correctly if the information referred to is correct and complete. In the unlikely event of incorrect or incomplete information provided by the Art Lover when entering into the Agreement, the Art Lover must notify MIB4u Gallery immediately. Moreover, MIB4u Gallery is never liable for damages suffered by the Art Lover due to incorrect or incomplete information provided by the Art Lover.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Without prejudice to the provisions of Article 4, each Agreement is binding after its conclusion; except insofar as provided for in the rest of these general terms and conditions, the Art Lover does not claim any remission or refund of the agreed payment.
                    </li>
                </ol>

                {/* Article 4 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 4. | RIGHT OF DISSOLUTION FOR CONSUMERS</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        The provisions of this article do not apply if the Seller does not act within the framework of the Agreement in the exercise of a profession or business. If, under the Agreement, the Seller is not acting in the course of a profession or business, this will be evident from the information in or accompanying the Offer.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Subject to the other provisions of this article, a Consumer may dissolve the Agreement for a period of 14 days after receipt of the Product, without giving reasons. The Consumer must invoke the right of dissolution in accordance with the provisions of paragraph 4 with:
                        <ol className='list-outside list-[lower-alpha] pl-[15px]' >
                            <li className='text-[15px] text-zinc-500' >
                                MIB4u Gallery if less than four days have elapsed since the day of delivery of the Product;
                            </li>
                            <li className='text-[15px] text-zinc-500' >
                                the relevant Seller if four days have already elapsed since the day of delivery of the Product.
                            </li>

                        </ol>
                    </li>

                    <li className='text-[15px] text-zinc-500' >
                        The Consumer has no right of dissolution in the event of:

                        <ol className='list-outside list-[lower-alpha] pl-[15px]' >
                            <li className='text-[15px] text-zinc-500' >
                                the delivery of Products manufactured according to the Consumer&apos;s specifications, which are not prefabricated and which are manufactured on the basis of an individual choice or decision of the Consumer, or which are clearly intended for a specific person;
                            </li>
                            <li className='text-[15px] text-zinc-500' >
                                the delivery of Products which, by their nature, have been irrevocably mixed with other items after delivery;
                            </li>
                            <li className='text-[15px] text-zinc-500' >
                                the delivery of Products in respect of which the right of dissolution is otherwise excluded by virtue of Section 6.5.2B of the Dutch Civil Code or does not apply, in which case this is explicitly stated in the Offer.
                            </li>
                        </ol>
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The Consumer who makes use of the right of dissolution, can dissolve the Agreement by submitting a request to MIB4u Gallery, respectively the Seller, by e-mail or by using the model revocation form. As soon as possible after the relevant party has been informed of the intention of the Consumer to dissolve the agreement and if the conditions of this article are met, that party will confirm the dissolution of the Agreement to the Consumer by e-mail.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        If the Consumer makes use of the right of dissolution, he must handle the Product in question and its packaging with care during the 14-day cooling-off period. The Consumer may only handle and inspect the Product to be returned to the Seller to the extent necessary to assess the nature and characteristics of the Product. The basic principle here is that the Consumer may only handle and inspect the Product as he would in a physical shop.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        If the Consumer makes use of the right of dissolution, he will return the Product to the Seller undamaged, with all delivered accessories and in its original condition and packaging. The Product must be returned by the Consumer within 14 days after dissolution of the Agreement in accordance with the provisions of paragraph 4.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The Consumer will be liable towards Seller for any reduction in value of the Product resulting from a way of dealing with the Product that goes beyond what is permitted under paragraph 5. The Seller is entitled to compensation of this reduction in value vis-à-vis the Consumer, whether or not by setting it off against the payment already received from the Consumer.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        If the Consumer makes use of the right of dissolution, the costs of returning the Product will be borne by the Consumer.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The party from whom the right of termination has been validly invoked in accordance with the provisions of paragraph 2, will refund the payment received from the Consumer, minus any reduction in value, to the Consumer as soon as possible, but no later than 14 days after termination of the Agreement, provided that the Product has been received back by the Seller or the Consumer has demonstrated to the party concerned that the Product has actually been returned. The party obliged to reimburse the Consumer shall not be obliged to reimburse the additional costs if the Consumer has expressly opted for a method of delivery other than the offered least costly standard delivery method when placing the order.
                    </li>

                </ol>

                {/* Article 5 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 5. | PERFORMANCE OF THE AGREEMENT AND DELIVERY OF THE PRODUCTS</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        The Product will be delivered to the delivery address provided by the Art Lover.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        If the Product could not be delivered as a result of a circumstance attributable to the Art Lover, any additional costs incurred as a result, such as extra delivery costs, shall be borne by the Art Lover.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Without prejudice to the obligations of MIB4u Gallery explicitly included in these general terms and conditions, only the Seller in question is liable towards the Art Lover for the fulfilment of his obligations arising from the Agreement. The Seller is responsible for the proper and timely execution of the Agreement in accordance with the instructions provided by MIB4u Gallery. Furthermore, the Seller shall be solely responsible for ensuring that the Products offered by him on the Platform comply with the Agreement, the specifications set out in the Offer, the reasonable requirements of soundness and usability and the legal provisions existing on the date on which the sale was concluded. MIB4u Gallery does not assume any liability for the Seller&apos;s shortcomings towards the Art Lover, on the understanding that the Art Lover may submit a substantiated complaint about the delivered Product to MIB4u Gallery by e-mail up to three days after delivery of the Product. If the Art Lover demonstrates that the Seller has failed to fulfil its obligation to deliver in accordance with the sale, MIB4u Gallery may determine that the Art Lover is entitled to a refund of the amount paid by it under the Contract and that the Contract is thereby dissolved. The the Art Lover is then obliged to return the Product to the Seller. MIB4u Gallery will inform the Art Lover about this and the Art Lover must comply with this obligation. The Art Lover indemnifies MIB4u Gallery against any claims by the Seller in question in connection with any failure to comply with the Art Lover&apos;s return obligations.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        After expiry of the period of three days as referred to in the previous paragraph, MIB4u Gallery can no longer be held liable by the Art Lover for shortcomings on the part of the Seller. The Art Lover must then contact the Seller directly.
                    </li>
                </ol>

                {/* Article 6 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 6. | SHORTCOMINGS AND FRAUD</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        If MIB4u Gallery has reasonable doubt that the Art Lover has not fulfilled or will not fulfil its (purchase) obligations under a Contract, MIB4u Gallery is entitled to cancel the Contract on behalf of the Seller. In that case, the payment already made by the Art Lover shall be refunded.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        In the event that the Art Lover otherwise infringes the provisions of these General Terms and Conditions, MIB4u Gallery is entitled to block the Art Lover&apos;s account on the Platform, and in the event of an Agreement already concluded, to dissolve the Agreement on behalf of the Seller, unless the relevant infringement does not reasonably justify the consequences thereof under the circumstances.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery can never be held liable for any damage caused to the Art Lover as a result of MIB4u Gallery exercising the rights referred to in the previous paragraphs of this article. If a Seller suffers damage as a result, the Art Lover indemnifies MIB4u Gallery against all claims of the Seller in question.
                    </li>

                </ol>

                {/* Article 7 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 7. | PAYMENTS</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        Before the Agreement is concluded, the total price, including VAT and any delivery costs, will be explicitly stated.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Payment must be made by one of the payment methods chosen for this purpose by the Art Lover when entering into the Agreement. After the conclusion of the Agreement, the Art Lover shall be irrevocably bound to its payment obligation, without prejudice to the provisions in the other provisions of these general terms and conditions.
                    </li>
                </ol>

                {/* Article 8 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 8. | LIABILITY OF ONLINE GALLERY AND INDEMNITY</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        Sellers determine the content of their Offer on the Platform. MIB4u Gallery is not obliged to ascertain whether the information provided by the Sellers, as published on the Platform, is unlawful, incorrect or misleading. MIB4u Gallery does not accept any liability in this respect.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery is not liable for damages resulting from unauthorized use of the Art Lover&apos;s login details to access its account on the Platform.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery makes every effort to optimize the correct operation and accessibility of the Platform. However, MIB4u Gallery cannot guarantee that the facilities on the Platform will always be available indefinitely and that all facilities on the Platform will always function smoothly. Any liability of MIB4u Gallery in this respect is excluded.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery is at all times authorized to (temporarily) put the Platform or parts thereof out of use if it deems this desirable in respect of maintenance, adaptation or improvement of the Platform or the servers of MIB4u Gallery or third parties on which the operation of the Platform depends. All liability of MIB4u Gallery as a result of the temporary inaccessibility of the Platform or parts thereof is excluded.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        If the Platform contains references, for example by means of hyperlinks, to websites of third parties, MIB4u Gallery is never liable for the content of these websites.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        MIB4u Gallery is in any case never liable for lost profit, losses, personal injury, other consequential loss or damage, loss of details and other moral damage, related to the use of the Platform and the other performance of the Service by MIB4u Gallery.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        The Art Lover indemnifies MIB4u Gallery against all its claims and claims of third parties (including Sellers) in connection with the performance of the Agreement, which claims relate to damage that cannot be attributed to MIB4u Gallery. Should MIB4u Gallery be called to account by a third party for this reason, the Art Lover is obliged to assist MIB4u Gallery both in and out of court and to immediately do everything that can reasonably be expected of him in that case. Should the Art Lover fail to take adequate measures, MIB4u Gallery is entitled to do so itself, without notice of default. All costs and damages on the part of MIB4u Gallery and/or third parties resulting from this, are integrally at the expense and risk of the Art Lover.
                    </li>
                </ol>

                {/* Article 9 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 9. | COMPLAINTS POLICY</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        The Art Lover must submit complaints about the Service to MIB4u Gallery in writing, in full and clearly described, within a reasonable period of the Art Lover discovering the grounds for the complaint
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Complaints submitted to MIB4u Gallery about the service will be answered within seven days of receipt. If a complaint requires a longer processing time, an answer will be given within the period of seven days with an acknowledgement of receipt and an indication of when the Art Lover can expect a more detailed answer.
                    </li>

                </ol>

                {/* Article 10 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 10. | INTELLECTUAL PROPERTY</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        All copyrights and other intellectual property rights to the Platform and its components, including the software, design and operation of the Platform and images displayed through the Platform, belong to MIB4u Gallery or its licensors, possibly including Sellers. Without the prior written consent of MIB4u Gallery or the respective licensor, it is prohibited to duplicate, reproduce, distribute, exploit or create derivative works from the material on which the rights of MIB4u Gallery or the respective licensor rest.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        In the event of a breach of the provisions of the previous paragraph attributable to the User, MIB4u Gallery or the licensor reserves all rights vested in it by law, including the right to claim reasonable damages and immediate cancellation of the breach.
                    </li>
                </ol>

                {/* Article 11 */}
                <h2 className='font-semibold text-zinc-400 mb-3' >ARTICLE 11. | CONCLUDING PROVISIONS</h2>
                <ol className='list-outside list-decimal mb-4' >
                    <li className='text-[15px] text-zinc-500' >
                        The Offer, Agreements, the use of the Platform and the Service are governed exclusively by Dutch law.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        In case a dispute arises between MIB4u Gallery and the Art Lover, they are obliged to make every effort to settle the dispute in mutual consultation.
                    </li>
                    <li className='text-[15px] text-zinc-500' >
                        Except to the extent compulsorily prevented by law, under the given circumstances of the case, only the competent court within the district of MIB4u Gallery&apos;s registered office will be designated to hear legal disputes between MIB4u Gallery and the Art Lover.
                    </li>
                </ol>




            </div>
        </div>
    )
}

export default TermsConditions